### ISSUE TITLE
Uncaught error during `optimize` with worker set to zero

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#19]
After optimization with bedrock-webpack, and with workers set to `0` in the config, there seems to be some issue shutting down child processes:

Node v6.11.3

```
2017-09-21T14:02:23.780Z - critical: master: uncaught error: Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:584:16)
    at Worker.send (cluster.js:64:28)
    at process.<anonymous> (/home/bedrock/veres-delta/node_modules/bedrock/lib/bedrock.js:409:27)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:164:15)
    at EventEmitter.<anonymous> (/home/bedrock/veres-delta/node_modules/bedrock/lib/bedrock.js:420:15)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at ChildProcess.<anonymous> (cluster.js:378:15)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)

```

**Comment by mattcollier** [comment]
Closing old obsolete issue.
