### ISSUE TITLE
`posix` fails to build on Node 10.x / posix removal

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock#24]
It appears that the only use for `posix` has to do with the logging system: https://github.com/digitalbazaar/bedrock/blob/master/lib/loggers.js#L98

How essential is the functionality?  Can bedrock do without a posix dependency?

There is one error at the beginning of the log and the rest are warnings:
```
> posix@4.1.1 install /home/matt/dev/bedrock-dev/bedrock-passport/test/node_modules/posix
> node-gyp rebuild

make: Entering directory '/home/matt/dev/bedrock-dev/bedrock-passport/test/node_modules/posix/build'
  CXX(target) Release/obj.target/posix/src/posix.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../src/posix.cc:1:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../src/posix.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:817:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../node_modules/nan/nan.h:47:0,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/matt/.node-gyp/10.0.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/posix.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:831:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../node_modules/nan/nan.h:47:0,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/matt/.node-gyp/10.0.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/posix.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:845:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../node_modules/nan/nan.h:47:0,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/matt/.node-gyp/10.0.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../src/posix.cc:1:0:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../node_modules/nan/nan.h:1453:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../node_modules/nan/nan.h:47:0,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/matt/.node-gyp/10.0.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_chroot(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:118:51: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value dir_path(info[0]->ToString());
                                                   ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_getrlimit(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:174:54: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value rlimit_name(info[0]->ToString());
                                                      ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_setrlimit(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:214:54: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value rlimit_name(info[0]->ToString());
                                                      ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_getpwnam(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:285:52: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
         String::Utf8Value pwnam(info[0]->ToString());
                                                    ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_getgrnam(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:326:52: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
         String::Utf8Value pwnam(info[0]->ToString());
                                                    ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_initgroups(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:366:47: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value unam(info[0]->ToString());
                                               ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_openlog(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:442:48: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value ident(info[0]->ToString());
                                                ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_syslog(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:474:50: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value message(info[1]->ToString());
                                                  ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_sethostname(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:583:34: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value str(info[0]);
                                  ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_swapon(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:609:34: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value str(info[0]);
                                  ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE node_swapoff(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/posix.cc:630:34: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     String::Utf8Value str(info[0]);
                                  ^
In file included from /home/matt/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/matt/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:47,
                 from ../src/posix.cc:1:
/home/matt/.node-gyp/10.0.0/include/node/v8.h:2822:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/matt/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
posix.target.mk:95: recipe for target 'Release/obj.target/posix/src/posix.o' failed
make: *** [Release/obj.target/posix/src/posix.o] Error 1
make: Leaving directory '/home/matt/dev/bedrock-dev/bedrock-passport/test/node_modules/posix/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/matt/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.9.0-6-amd64
gyp ERR! command "/home/matt/.nvm/versions/node/v10.0.0/bin/node" "/home/matt/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/matt/dev/bedrock-dev/bedrock-passport/test/node_modules/posix
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

**Comment by davidlehn** [comment]
Lot's of noise in that output.  Looks like just one nan error?  Perhaps the strict 2.4.x nan dep is too old to support newer nodes.  There are some other options that might work like `posix-ext`.  We're just using it to lookup a uid from a user name.  It's useful to have this chown functionality when starting as root since the log files are opened before it drops privileges.  Maybe not needed in the more recent usage pattern of starting as non-root.

**Comment by mattcollier** [comment]
@davidlehn I'm willing to say that the current deployment patter of starting as a non-root user is a best practice and therefore this feature is definitely a candidate for the chopping block IMO.  

Also wrt to that feature, has the issue of worker crashes that result in workers failing to restart due to privilege elevation been solved permanently?

**Comment by davidlehn** [comment]
I'm not sure about the restart issue.  I think there still can be edge case failures depending on setup and file permissions and such.

**Comment by mattcollier** [comment]
No longer an issue.
